<?php
  //Php basics
  /*
     # Author: Dharma Raj Poudel
     # Author URL: drpoudel.com.np
     # Basic codes for php
  */
  echo "Good Morning All";
  echo "<br/>";
  echo "<h1>Basics of PHP</h1>";
  $name = "Dharma";
  echo "<br/> The code is generated by $name";
  echo '<br/> The code is generated by $name';
  echo "<br/> The code is generated by". $name;
  echo '<br/> The code is generated by'. $name;

  //to get the data types use gettype() function in php
echo gettype($name);
$a = 20;
echo "<br/>" . gettype($a);
$a = 25;
$b = 30;
$c = $a + $b;
echo "<br/>The sum of $a and $b is $c";
echo '<br/>The sum of' .$a. ' and ' .$b. ' is ' .$c;

$price=2.35;
$qty=7.35;
$amount= $price * $qty;

echo "<br/> The total amount is $amount"; 
echo "<br/> The total amount is " .number_format($amount, 2); 



?>